# fly.toml app configuration file generated for lstm-code-gen on 2024-10-10T14:03:31Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'lstm-code-gen'
primary_region = 'ewr'

[build]

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
